### ISSUE TITLE
Erro while building during install

### ISSUE THREAD

**Issue by afucher** [mivion/swisseph#1]
Hi,

First I need to do: '''npm install swiseph --python'''

Because I have Python 3.3 installed.

But with this, I'm get this error:
LINK : fatal error LNK1149: output filename matches input filename 'C:\Projeto\
testes\node_modules\swisseph\build\Release\swisseph.lib' [C:\Projeto\testes\nod
e_modules\swisseph\build\swisseph.vcxproj]

![image](https://f.cloud.github.com/assets/3756185/1674448/7e4f7e82-5cf9-11e3-80a5-705ef80696bd.png)

**Comment by JamesHagerman** [comment]
I'm not sure why this was closed because it was still not working for me. I put in a pull request that should fix this issue behind the scenes. I'm sure there are better ways to handle this but at least it installs and seems to work now!

**Comment by mivion** [comment]
Hi.
I've accepted your pull request.
Let me know if this problem is fixed.

**Comment by JamesHagerman** [comment]
Sorry for the delay! This change works!

Another release will need to be tagged for others to use this right?

**Comment by mivion** [comment]
Yes.
New version released 0.5.3.
I'll publish it to npm today.

**Comment by mivion** [comment]
npm package published.
