### ISSUE TITLE
The functions of the houses do not calculate the "G" type (Gauquelin)

### ISSUE THREAD

**Issue by blucobalto** [mivion/swisseph#11]
Hi Mivion,
some days I'm using swissep for nodejs.
So far so good, except for one problem.

The calculation functions of the houses using an array of 12 elements. But for the type "G" (Gauquelin) array of 36 elements are required.

Thanks a lot,
blu

**Comment by mivion** [comment]
Hi,

Thanks for interesting.
What function do you mean for 36 elements?

**Comment by blucobalto** [comment]
Hi,
Taken from the file "../doc/swephprg.htm":

Section 12. House cusp calculation
swe_houses()
swe_houses_armc()
swe_houses_ex()
...
Also note that the array cusps must provide space for 13 doubles (declare as cusp[13]), otherwise you risk a program crash. With house system ‘G’ (Gauquelin sector cusps), declare it as cusp[37]. 

Note: With house system ‘G’, the cusp numbering is in clockwise direction.
...

Thanks a lot,
blu

**Comment by mivion** [comment]
Hi,

This should work with current API and swisseph version.

**Comment by mivion** [comment]
Hi,

Thanks for reporting this bug.
The bug fixed, also added tests for it. See new version 0.5.5.
Please report if all right now.

**Comment by blucobalto** [comment]
Hi,
Awesome. I tested the software and it works very well.
The problem with the calculation of the houses (Gauquelin) is solved.
I noticed that you've updated to the latest versions. 
Thanks you very much for your valuable work.

Cheers,
blu

**Comment by mivion** [comment]
Hi,

Thanks for reply, bug ready to close. )
