### ISSUE TITLE
Support iojs by first moving to nan@2, and thereby support electron

### ISSUE THREAD

**Issue by charandas** [mivion/swisseph#15]
Hi there,

I forked swisseph today to start migrating the code to nan@2. It compiles with node 0.12+ and the tests pass, but I cannot get it to build with electron's [iojs](https://atom.io/download/atom-shell).

Its boiling down to [L8](https://github.com/charandas/swisseph/blob/master/src/callback.cc), I want to ask what exactly are we saving into argv[1], what do the curly braces do, and do you see any incomplete type information being passed to the templating engine given nan2 docs. Iojs node-gyp build is reporting incomplete type info here.

Any help is appreciated. Cannot wait to run swisseph directly from the browser with electron taking care of the remote calls.

**Comment by charandas** [comment]
Actually @mivion. I found [this](https://github.com/nodejs/nan/issues/401) and figured it out.

The curly braces are just an initializer list - so I get that now.

A PR coming your way.

**Comment by mivion** [comment]
Hi,

Glad to see problem is solved. Waiting for PR.
Thanks.
