### ISSUE TITLE
error C2995: function template has already been defined

### ISSUE THREAD

**Issue by JVerstry** [mivion/swisseph#18]
I am facing compilation issues when npm installing swisseph for a node project. Apparently, some files are compiled properly, then it fails:

    ...
    swemplan.c
    sweph.c
    swephlib.c
    win_delay_load_hook.c
    swissephz.vcxproj -> C:\... \node_modules\swisseph\build\Release\\swissephz.lib
    util.cc
    date.cc
    C:\... \node_modules\swisseph\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)' : function template has already been defined (..\src\date.cc) [C:\... \node_modules\swisseph\build\swisseph.vcxproj]
          C:\... \node_modules\swisseph\node_modules\nan\nan.h(319) : see declaration of 'Nan::imp::NanEnsureHandleOrPersistent'
    C:\... \node_modules\swisseph\node_modules\nan\nan.h(346): error C2995: 'v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)' : function template has already been defined (..\src\date.cc) [C:\... \node_modules\swisseph\build\swisseph.vcxproj]
          C:\... \node_modules\swisseph\node_modules\nan\nan.h(334) : see declaration of 'Nan::imp::NanEnsureLocal'
    C:\... \node_modules\swisseph\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)' : function template has already been defined (..\src\util.cc) [C:\... \node_modules\swisseph\build\swisseph.vcxproj]
          C:\... \node_modules\swisseph\node_modules\nan\nan.h(319) : see declaration of 'Nan::imp::NanEnsureHandleOrPersistent'
    C:\... \node_modules\swisseph\node_modules\nan\nan.h(757): error C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\date.cc) [C:\... \node_modules\swisseph\build\swisseph.vcxproj]
    C:\... \node_modules\swisseph\node_modules\nan\nan.h(346): error C2995: 'v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)' : function template has already been defined (..\src\util.cc) [C:\... \node_modules\swisseph\build\swisseph.vcxproj]
    ...

I am on node 4.1.1 and npm 2.14.4 and node-gyp 3.0.3. I have Microsoft Visual Express 2013 for Desktop installed on my PC (Windows 10 - 32 bits).

**Comment by mivion** [comment]
Hi,

Is this problem exists on prev version of node?

**Comment by JVerstry** [comment]
I have encountered several compilation issues on previous versions of node. Some were related to node_gyp, other to the version of the Microsoft Visual C++ compiler on Windows. I read about solution and they pointed to update the latest version on node, which contains the latest version of node_gyp fixing some issues.

I don't think this is node related. Which compiler has been used to test the compilation of the code? Has it been tested on Windows?

**Comment by mivion** [comment]
Please, try new version from master branch.

**Comment by JVerstry** [comment]
Your version in your package.json is 0.5.6. However, when I add this dependency in my project, npm does not find it. I have checked https://www.npmjs.com/package/swisseph, it still reports the latest version as 0.5.5. Can you fix this?

**Comment by mivion** [comment]
Published fresh version.

**Comment by JVerstry** [comment]
Error has disappeared with 0.5.6, many thanks !!!
