### ISSUE TITLE
Can't install swisseph

### ISSUE THREAD

**Issue by wizysanjay** [mivion/swisseph#20]
Dear I have got this msg when i try install swisseph on Centos 7, python 2.7, nodejs 4.2.1, npm 2.14.7 
How do I fix this

make: Leaving directory `/home/user/node_modules/swisseph/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.14.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node_modules/swisseph
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-229.14.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "swisseph"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! swisseph@0.5.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swisseph@0.5.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the swisseph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls swisseph
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/npm-debug.log

**Comment by mivion** [comment]
Try latest version from master. Is it working?

**Comment by mivion** [comment]
Try latest version.

**Comment by wizysanjay** [comment]
I tried the latest version, It's already working but has a warning 

../src/swisseph.h:4:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (disable : 4251)

**Comment by mivion** [comment]
This warning not critical, and related to original swisseph sources.

**Comment by wizysanjay** [comment]
Thanks !
