### ISSUE TITLE
SEFLG_EQUATORIAL and SEFLG_XYZ positions are not reported properly

### ISSUE THREAD

**Issue by JVerstry** [mivion/swisseph#23]
While performing the following test:

```
var swisseph = require("swisseph");
var assert = require("assert");

// Test date 
var date = {year: 2012, month: 1, day: 1, hour: 0};
console.log("Test date:", date);

var flag = swisseph.SEFLG_MOSEPH;

var julday_ut = swisseph.swe_julday(date.year, date.month, date.day, date.hour, swisseph.SE_GREG_CAL);

assert.equal(julday_ut, 2455927.5);
console.log("Julian UT day for date:", julday_ut);

// Sun position 
var body = swisseph.swe_calc_ut(julday_ut, swisseph.SE_SUN, flag);
assert(!body.error, body.error);
console.log("Sun position:", body);

var flag2 = swisseph.SEFLG_EQUATORIAL | swisseph.SEFLG_MOSEPH;

// Sun position 
var body2 = swisseph.swe_calc_ut(julday_ut, swisseph.SE_SUN, flag2);
assert(!body2.error, body2.error);
console.log("Sun position 2:", body2);
```

I have noticed it returns longitude and latitude:

```
Julian UT day for date: 2455927.5
Sun position: { longitude: 279.95830174524593,
  latitude: 0.0002633192811012996,
  distance: 0.9833296457898204,
  longitudeSpeed: 0,
  latitudeSpeed: 0,
  distanceSpeed: 0,
  rflag: 4 }
Sun position 2: { longitude: 280.83338002747627,
  latitude: -23.062912656952832,
  distance: 0.9833296457898204,
  longitudeSpeed: 0,
  latitudeSpeed: 0,
  distanceSpeed: 0,
  rflag: 4 }
```

instead of rectascension, declination, etc... as mentioned in the swisseph documentation: http://www.astro.com/swisseph/swephprg.htm#_Toc433200761

The same issue happens with SEFLG_ZYX. It does not return x, y, z, dx, dy, dz...

**Comment by mivion** [comment]
Hi,

I've changed names for return values:
x -> longitude
y -> latitude
z -> distance
dx -> longitudeSpeed
dy -> latitudeSpeed
dx -> distanceSpeed

**Comment by JVerstry** [comment]
I have tried with release 5.7.0. The issues are not solved, neither for SEFLG_ZYX and nor for SEFLG_EQUATORIAL.

**Comment by mivion** [comment]
I mean that return values are normal.
longitude means x
latitude means y
and so on, as mentioned above.

**Comment by knyazhe1** [comment]
u right, @mivion!
but it is not good in cleared code, i think.
for example: it will be bad understanding other javascript programmers.
original source of **calc_ut** return **xx[6]** values, but it is bad too :grinning:
named property is better for me :thumbsup:
i can make PR for this issue, but this flag bits using in other methods too.
if somebody will make a full testing script for flag bits in all module methods :eyes:

**Comment by mivion** [comment]
Yes, this is the problem.
We also can return x[6] too, but this solution is bad.
Also we can change the API to return only xx[6] as in original swisseph API, as you suggest, but if some one already uses this API then this is a problem.
Can some one report any problem with current implementation?
Any suggestions?

**Comment by knyazhe1** [comment]
> Also we can change the API to return only xx[6] as in original swisseph API, as you suggest, but if some one already uses this API then this is a problem.

no!
something about
```javascript
	if (rflag < 0) {
		result->Set (Nan::New<String> ("error").ToLocalChecked(), Nan::New<String> (serr).ToLocalChecked());
	} else {
			if(rflag | SEFLG_EQUATORIAL)
				result->Set (Nan::New<String> ("rectascension").ToLocalChecked(), Nan::New<Number> (x [0]));
				...
			} else {
				if(rflag | SEFLG_XYZ)
					result->Set (Nan::New<String> ("x").ToLocalChecked(), Nan::New<Number> (x [0]));
				} else {
					result->Set (Nan::New<String> ("longitude").ToLocalChecked(), Nan::New<Number> (x [0]));
```

**Comment by gordalina** [comment]
Such a change in the API warrants a major version upgrade (in this case to 1.0).
I'd be very careful about the way this is approached.

**Comment by mivion** [comment]
@knyazhe1 looks good. would you prepare PR for these changes?
@gordalina yes, these changes should upgrade major version.

Also I think we eventually have to release 1.0 version, as it seems to very stable now.

What do you think?

**Comment by gordalina** [comment]
:+1: for 1.0

**Comment by knyazhe1** [comment]
well, i will make PR for this issue too.
and yes, current version ready for release 1.0.
my little misunderstandind only about purpose of **lib/swisseph.js::calc** :confused:

what next in ver.2.0? :rocket:

**Comment by mivion** [comment]
thank you, waiting for PR.

function **lib/swisseph.js::calc** is util function, it calculates all times, select ephemeris, and so on.
just help function to calculate all things for one planet.

about plans, I want to launch online service http://swisseph.com, and open online API for all functions.

**Comment by mivion** [comment]
Merged to master branch.
Please report if some problems.

**Comment by JVerstry** [comment]
I'll check it when I can compile the dependency again on x64 platform.

**Comment by mivion** [comment]
Any progress?
