### ISSUE TITLE
error MSB8007: The Platform for project XXX is invalid. Platform='x64'

### ISSUE THREAD

**Issue by JVerstry** [mivion/swisseph#27]
Hi, I have recently switched from a 32 bits PC to a 64 bits PC and the C++ compilation process does not work anymore. I have described this in a [StackOverflow](http://stackoverflow.com/questions/34473592/error-msb8007-the-platform-for-project-xxx-is-invalid-platform-x64) question.

The main error message is: 

    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7):
    error MSB8007: The Platform for project 'swissephz.vcxproj' is invalid.  Platform='x64'.

The full error message is available in the StackOverflow question. How can we solve this?

**Comment by knyazhe1** [comment]
this is not a problem of swisseph :) 
https://www.npmjs.com/package/node-gyp#installation
>Microsoft Visual Studio C++ 2013 (Express version works well)
>    If the install fails, try uninstalling any C++ 2010 x64&x86 Redistributable that you have installed first
>    If you get errors that the 64-bit compilers are not installed you may also need the compiler update for the Windows SDK 7.1
...
>For 64-bit builds of node and native modules you will **also** need the Windows 7 64-bit SDK

**Comment by mivion** [comment]
Hi,

Thanks for sharing this.
