### ISSUE TITLE
something is missing in the "eclipse.cc"

### ISSUE THREAD

**Issue by knyazhe1** [mivion/swisseph#29]
firstly, method **swe_lun_eclipse_when_loc** missing in the **src/eclipse.h** and **src/eclipse.cc**
(see http://www.astro.com/swisseph/swephprg.htm#_Toc433200779).

secondary, property **retFlag** is not present in the result of calls of this module.
but this value is very important for eclipses and occultations detail!

```cpp
/* retflag -1 (ERR) on error (e.g. if swe_calc() for sun or moon fails)
   SE_ECL_TOTAL or SE_ECL_ANNULAR or SE_ECL_PARTIAL or SE_ECL_ANNULAR_TOTAL
   SE_ECL_CENTRAL
   SE_ECL_NONCENTRAL
   SE_ECL_VISIBLE,
   SE_ECL_MAX_VISIBLE,
   SE_ECL_1ST_VISIBLE, SE_ECL_2ND_VISIBLE
   SE_ECL_3ST_VISIBLE, SE_ECL_4ND_VISIBLE
  ... etc. etc.
```
probably this is already will be fixed in the next build?

**Comment by mivion** [comment]
Hi,

Thanks for report.
There also function **swe_rise_trans_true_hor** is missing.
Will be added as soon as possible.
The **retFlag** will be resolved in separate issue.

**Comment by knyazhe1** [comment]
i will add **swe_rise_trans_true_hor** too (in couple day) + minor changes in **examples/eclipses.js**

**Comment by mivion** [comment]
thanks a lot.
