### ISSUE TITLE
Failed at the swisseph@0.5.7 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by spiritguide7** [mivion/swisseph#33]
Updated to node v5.7.0
Windows 10 64bit
reinstalled node-gyp - No problem
[npm-debug.txt](https://github.com/mivion/swisseph/files/151981/npm-debug.txt)

C:\Users\Jack\Documents\nodejs\astronode>npm install swisseph
npm WARN package.json astronode@1.0.0 No repository field.
npm WARN package.json astronode@1.0.0 No README data
\

> swisseph@0.5.7 install C:\Users\Jack\Documents\nodejs\astronode\node_modules\swisseph
> node-gyp rebuild

C:\Users\Jack\Documents\nodejs\astronode\node_modules\swisseph>if not defined npm_config_node_gyp (node "C:\Us
ers\Jack\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node  rebuild )
gyp: C:\Users\Jack.node-gyp\5.7.0\common.gypi not found (cwd: C:\Users\Jack\Documents\nodejs\astronode\node_m
odules\swisseph) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Jack\AppData\Roaming\npm\node_modules\npm\node_modules\n
ode-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Jack\AppData\Roaming\npm\node_modules\
npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jack\Documents\nodejs\astronode\node_modules\swisseph
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Jack\AppData\Roaming\npm\node_modules\npm
\bin\npm-cli.js" "install" "swisseph"
npm ERR! node v5.7.0
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! swisseph@0.5.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swisseph@0.5.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the swisseph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls swisseph
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jack\Documents\nodejs\astronode\npm-debug.log

C:\Users\Jack\Documents\nodejs\astronode>

**Comment by mivion** [comment]
Hi,

thanks for report, but the v5.x does't support yet due to nan project.
I working on it.

**Comment by spiritguide7** [comment]
Thanks Mikhail.

I was able to install an older version of nodejs and things worked 
perfectly.

I though it had to do with the 256 byte limit for full path names on 
Windows and the load module.

Please let me know when I can try again.

Thank you
Jack

**Comment by asotirov** [comment]
@spiritguide7 Which version of node worked for you? 
I have been trying to install swisseph on a node version >= 4.0.0, unsuccessfully for about 3 hours now.

Thanks,
Anton

**Comment by flasomm** [comment]
@asotirov Hi use node v6.7.0. And it works like a charm.
Fabrice

**Comment by spiritguide7** [comment]
I was able to successfully compile and install on Win 10 install after issuing this command:
npm config set msvs_version 2013 --global

node v6.7.0
npm 3.10.7

**Comment by a4ankii** [comment]
@mivion Hi, i am using node v6.7.0 and npm 5.3.0.
I have been trying to install swisseph using command - npm install swisseph.
But it is giving me following errors.

C:\ProgramFiles\nodejs>npm install swisseph
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue

> swisseph@0.5.7 install C:\Program Files\nodejs\node_modules\swisseph
> node-gyp rebuild


C:\Program Files\nodejs\node_modules\swisseph>if not defined npm_config_node_gyp
 (node "C:\Users\aa\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\aa\AppData\Roaming\npm\node_
modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\aa\AppData\Roaming\npm\node_m
odules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\aa\AppData\Roaming\npm\node_modules\npm\node_modu
les\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aa\\AppData\\
Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebu
ild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\swisseph
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swisseph@0.5.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swisseph@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aa\AppData\Roaming\npm-cache\_logs\2017-08-02T23_19_54_552
Z-debug.log

**Comment by keel** [comment]
I think you need install python first.

**Comment by a4ankii** [comment]
@keel i have just installed python3.1.1 but now the error log is

C:\Program Files\nodejs>npm install swisseph
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or hig
to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or hi
 to avoid a RegExp DoS issue
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: har-schema@1.0.5 (node_modul
ar-schema):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not
itted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: co@4.6.0 (node_modules\co):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not
itted, mkdir 'C:\Program Files\nodejs\node_modules\.staging'

npm ERR! path C:\Program Files\nodejs\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\node
ode_modules\.staging'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Program Files\n
s\node_modules\.staging'
npm ERR!     at Error (native)
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, mkdir 'C:\Program Files
ejs\node_modules\.staging'
npm ERR!        at Error (native)
npm ERR!      type: 'OperationalError',
npm ERR!      '$error': '$error',
npm ERR!      cause:
npm ERR!       { errno: -4048,
npm ERR!         code: 'EPERM',
npm ERR!         syscall: 'mkdir',
npm ERR!         path: 'C:\\Program Files\\nodejs\\node_modules\\.staging' }
npm ERR!      isOperational: true,
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: 'C:\\Program Files\\nodejs\\node_modules\\.staging' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, mkdir \'C:\\Progra
les\\nodejs\\node_modules\\.staging\'\n    at Error (native)',
npm ERR!   type: 'OperationalError',
npm ERR!   '$error': '$error',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.staging',
npm ERR!   parent: 'nodejs' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aa\AppData\Roaming\npm-cache\_logs\2017-08-03T02_01_34
Z-debug.log

**Comment by keel** [comment]
Try to  change the work directory, like `D:\projectA` , please don't work under `C:\Program Files`.

**Comment by a4ankii** [comment]
I tried on mac  and it worked.
