### ISSUE TITLE
node-gyp rebuild failed on Node 4.4.3

### ISSUE THREAD

**Issue by chandantiwari** [mivion/swisseph#35]
I am getting the following error when npm installing swisseph on Node version 4.4.3 (Mac OS Maverick):  

`ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/swisseph.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chandan/Projects/node-express-boilerplate/node_modules/swisseph
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "swisseph" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE

npm ERR! swisseph@0.5.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swisseph@0.5.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swisseph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swisseph
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swisseph
npm ERR! There is likely additional logging output above.`

**Comment by mivion** [comment]
Hi,

Please use older version of node.
Sorry for that, I'll fix this issue.

**Comment by mivion** [comment]
Can anyone provide PR for upgrade node version?

**Comment by mivion** [comment]
The very old issue, node 4 unsupported.
