### ISSUE TITLE
SWE_HOUSES calculation help

### ISSUE THREAD

**Issue by DoctorHowser** [mivion/swisseph#37]
Hey Folks,

I'm riding the struggle bus, and I cant figure out why swe_houses is returning a different location for the houses than other astrology tools I'm using to check accuracy.  See attached doc, but everywhere I go for this data it says 14 07'01" (near 14.1), including the chart, and yet swe_houses spits out 13.351. In this case they aren't that far off, but in another the difference puts them in different signs. I've double checked input values, and they seem to be accurate. I've been reading the docs and I don't see any setting that I'm missing. I tried swe_houses_ex and got the same result. 

Anyone have experience with calculating houses? Or found house calculations differing?

relevant code:
```
//  julday_ut = 2445789.1666666665; //1984-03-29T16:07:00.000+00:00
        //  location = {
        //     lat : 40.97916667, // 40N 58'45"
        //     lon : -74.11694444 // 74W 7'1"
        // };

swisseph.swe_houses(julday_ut, location.lat, location.lon, 'P', function (result) {
            //etc
}

```

![image](https://cloud.githubusercontent.com/assets/11574995/23005929/97a75dc2-f3c4-11e6-868d-5a1ed1647bb5.png)

**Comment by DoctorHowser** [comment]
Lol, come ride it. Its because swe_julday doesn't take minutes. It will be off by the amount of minutes. I'll have to use swisseph.swe_utc_to_jd()

**Comment by dominiquemb** [comment]
Hey I asked Google Gemini about this and here's what it said (in case anyone comes across this via Google):

> The original author of that issue was likely passing an integer for the hour, thus losing the precision from the minutes and seconds.
> 
> What About swe_utc_to_jd()?
> The function sweph.swe_utc_to_jd() is simply a convenience function that does the decimal conversion for you internally. It takes the year, month, day, hour, minute, and second as separate arguments and returns the exact same Julian Day value that your current code produces.
> 
>
