### ISSUE TITLE
"Can't find variable: __dirname" when using in React-Native

### ISSUE THREAD

**Issue by mintproduct** [mivion/swisseph#38]
npm version: 4.1.2
node version: 7.7.4  or  0.12.8
React-Native version: 0.42

Hi mivion. I have encountered an error after Installing and using swisseph module in a React-Native project. The message is "Can't find variable: __dirname" 

Could you give me some suggestion?

**Comment by mivion** [comment]
Hi, the __dirname is used to get folders of ephemeris, and this variable included in nodejs since 0.1.27. (https://nodejs.org/docs/latest/api/globals.html#globals_dirname)
You have to find why react-native doesn't provide this variable.

**Comment by mintproduct** [comment]
Thanks for your comment @mivion .

**Comment by mintproduct** [comment]
Thanks for your help @mivion . 
I've realized that React-Native doesn't support ’.node‘ file. Which means that this nodejs version of swisseph cannot be used with RN.

**Comment by mivion** [comment]
Ok. Closing.
