### ISSUE TITLE
How can I call getTransitUt from original swisseph

### ISSUE THREAD

**Issue by asotirov** [mivion/swisseph#39]
Hi!

We need to calculate 2 things:

- retrograde shift dates 

- longitude return points. 

I've looked around and saw the getTransitUt method in the original swisseph implementation.

**How can I include a binding for node.js in node-swisseph for getTransitUt?**

Great work on this node package! Thank you!

This is a quote from [using TCPlanet](http://www.th-mack.de/download/swisseph-doc/swisseph/TCPlanet.html) in the original documentation.
> 
> You would create a TransitCalculator from this class and use the SwissEph.getTransit() methods to actually calculate a transit, e.g.:
> 
>  SwissEph sw = new SwissEph(...);
>  ...
>  int flags = SweConst.SEFLG_SWIEPH |
>              SweConst.SEFLG_TRANSIT_LONGITUDE |
>              SweConst.SEFLG_TRANSIT_SPEED;
>  boolean backwards = false;
>  
>  TransitCalculator tc = new TCPlanet(
>                                   sw,
>                                   SweConst.SE_SATURN,
>                                   flags,
>                                   0);
>  ...
>  double nextTransitET = sw.getTransitET(tc, jdET, backwards);
>  
> This would calculate the (ET-) date, when the Saturn will change from retrograde to direct movement or vice versa.

**Comment by mivion** [comment]
Could you provide PR?

**Comment by asotirov** [comment]
Unfortunately, no.

I am not sure how the bindings are being done in node.js.

Maybe you can point me to a resource or a commit that I can mimic and try to implement it.

**Comment by asotirov** [comment]
any feedback on the issue with the transits? :+1:

**Comment by mivion** [comment]
See source code at folders "deps/swisseph" is the sources from swisseph and "src" folder contains binding code.
