### ISSUE TITLE
enter

### ISSUE THREAD

**Issue by miquael** [mivion/swisseph#4]
Hello, I've successfully installed and running swisseph, tho am confused by the index.html.  Says "Help: enter a value and press <Enter> to make calculations" tho pressing Enter does nothing.  What is missing?

**Comment by mivion** [comment]
Hello,
What browser and OS?

**Comment by miquael** [comment]
Hi, I tried it in both FireFox and Chrome on OSX ... everything appears about right except there is not way to press 'Enter' ?

**Comment by mivion** [comment]
Hi,
Is there any error in javascript console? (cmd+alt+i in chrome on osx)
Maybe screenshot will help?

**Comment by miquael** [comment]
Okay, I've tried this with running different entry points:
node test.js (from within src - which i get errors in the terminal)
node index.js (from within public - no feedback is given)
node app.js (from within root - i assume this is the best way to go, as it successfully runs on port 3000)
In any case, I get the same result (here is a screenshot from running http://localhost:3000/index.html):

![image 2015-01-24 at 1 39 31 pm](https://cloud.githubusercontent.com/assets/158491/5889146/8620cdce-a3ce-11e4-974e-672d263334b2.png)



Does this require running node index.js ?  I tried both with same result.
Also, I tried running node test.js (from within src), and got these error:

**Comment by miquael** [comment]
This is terminal error I get when running node test.js:

Indra-5:swisseph mac$ node test

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph/test'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Tho seems like running node app.js is the way to go anyway?

**Comment by mivion** [comment]
To run the script you have to be in test directory and then run:
> node test.js

**Comment by mivion** [comment]
Also you can user:
> npm test

**Comment by miquael** [comment]
getting errors with those commands:

$:test mac$ node test.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph/lib/swisseph.js:1:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
$:test mac$ npm test

> swisseph@0.4.1 test /Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph
> node test/test.js

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph/lib/swisseph.js:1:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Test failed.  See above for more details.
$:test mac$

**Comment by miquael** [comment]
i removed it, then installed again:

$ npm install swisseph

it would not install, concluding in this error:

1 warning generated.
  SOLINK_MODULE(target) Release/swisseph.node
  SOLINK_MODULE(target) Release/swisseph.node: Finished
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "swisseph"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package yo does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-famous@0.2.23 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-meanjs@0.1.12 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-mocha@0.1.3 wants yo@>=1.0.0-rc.1.1
npm ERR! peerinvalid Peer generator-webapp@0.4.6 wants yo@>=1.0.0-rc.1.1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/_INTRA/_APPS/AION/ephemeris_engines/npm-debug.log

**Comment by miquael** [comment]
the npm-debug.log is 9074 lines long !!!
