### ISSUE TITLE
N-API support for Node.js 8

### ISSUE THREAD

**Issue by vshymanskyy** [mivion/swisseph#42]
Are there any plans to support N-API? I think it can **drastically** simplify binary packages deployment ;)

https://medium.com/the-node-js-collection/n-api-next-generation-node-js-apis-for-native-modules-169af5235b06

**Comment by mivion** [comment]
Yes, it's a very nice.
Need help.

**Comment by mivion** [comment]
Waiting stability of API.

**Comment by mivion** [comment]
Closing due inactivity...
