### ISSUE TITLE
Chiron position calculation is giving  error

### ISSUE THREAD

**Issue by a4ankii** [mivion/swisseph#44]
while running the code 
swisseph.swe_calc_ut (julday_ut, swisseph.SE_CHIRON, flag, function (body) {
  assert (!body.error, body.error);
  console.log ('Chiron position:', body);
 });

giving me error as follow
SwissEph file 'seas_18.se1' not found in PATH.....

**Comment by keel** [comment]
You can find a seas_18.se1 , copy it to your PATH, maybe here:
https://github.com/skypher/cerridwen/tree/master/sweph

**Comment by a4ankii** [comment]
I tried this but same error occurs 
AssertionError [ERR_ASSERTION]: SwissEph file 'seas_18.se1' not found in PATH '/Users/..../../ephe/

**Comment by keel** [comment]
make sure your file is in the right place, check the error message's path.

**Comment by a4ankii** [comment]
Umm! yes i changed the ephe folder path and it worked.
