### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by tranvansang** [mivion/swisseph#45]
Npm package is still old version 0.5.7
https://www.npmjs.com/package/swisseph

Please update it or add me to the collaborators list. I think I can help.

My npm username is "tranvansang"

**Comment by mivion** [comment]
You added to collaborators list.
Thank you for help.

**Comment by tranvansang** [comment]
Thank for the invitation.
Could you add me to collaborators list in npmjs page. I can help update npm package to the latest version.

How to do:

- Follow this link https://www.npmjs.com/package/swisseph
- Login
- In collaborators list in right panel, click Edit
- Add me to the list. My account is : tranvansang

Hope I can help
