### ISSUE TITLE
Failed to fetch Chiron data

### ISSUE THREAD

**Issue by albertkai** [mivion/swisseph#46]
Updated node_modules and started to get the error for Chiron: `error: 'SwissEph file \'seas_18.se1\' not found in PATH \'/Users/user/projects/microcosm_alpha/app/node_modules/swisseph/ephe/\''`. All other planets are ok!

**Comment by keel** [comment]
Chiron is not a basic planet. You need the seas_18.se1 ,  maybe here:
https://github.com/skypher/cerridwen/tree/master/sweph
Then copy it to your PATH.

**Comment by albertkai** [comment]
@keel great, thank you, that worked! Maybe also makes sense to add that file to the module, as the Chiron flag is defined, but the actual data fetching fails without additional more data (as you described)

**Comment by mivion** [comment]
Lets add it.

**Comment by keel** [comment]
That has been done.

**Comment by MarinChernyak** [comment]
Hello!
I am experiencing the same problem. I am using VS2012/WinForms/C#
bool f1 = File.Exists(@"C:\SWEPH\ephe\seas_18.se1");
f1 is true
sweph.swe_set_ephe_path(@"C:\SWEPH\ephe\");
 iflgret = sweph.swe_calc_ut(JD, SE_CHIRON, Constants.SEFLG_SPEED, dCoordinates,ref serr);
the message: SwissEph file 'seas_18.se1' not found in PATH 'C:\SWEPH\ephe\'
I have downloaded the file from GitHub...
What is wrong?
Thanks for advance!

**Comment by monolithed** [comment]
+1 when the `Swisseph.SEFLG_MOSEPH` flag is used
