### ISSUE TITLE
cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by timotejroiko** [mivion/swisseph#47]
my app is running it fine in a windows machine with node-webkit and nw-gpy. now im trying to port it into pure nodejs to use in a linux VPS.

The standard "npm install swisseph" works fine, but its version 2.02, not the latest swisseph 2.06
i tried both "npm install swisseph-new" and "npm install swisseph-zp", as well as downloading the zip package and running "node-gyp rebuild". all of them build but give the following error when running:
```
genesis@genesis-virtual-machine ~/astrobot $ node index.js
module.js:641
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/genesis/astrobot/node_modules/swisseph-new/build/Release/swisseph.node: cannot allocate memory in static TLS block
    at Object.Module._extensions..node (module.js:641:18)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/genesis/astrobot/node_modules/swisseph-new/lib/swisseph.js:1:78)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)

```

**Comment by keel** [comment]
That is not the swisseph's issue, you can try to update glibc on your server, if your vps is CentOS ,you can try `yum update -y`. 
checkout https://github.com/nodesource/distributions/issues/513

**Comment by timotejroiko** [comment]
@keel Thanks for your response. im running linux mint 18, glibc version 2.23
the older version of swisseph present in npm works fine. was there a change in glibc between swisseph versions?

**Comment by keel** [comment]
swisseph-new is my work to update to swisseph to 2.0.6, (sorry mivion, I need this version at that time),  now mivion have done the update, so I reset it to mivion's version, but mivion forgot to push to npm.

@mivion please push this version to npm, so we can use the current version.

@timotejroiko you can try to update swisseph-new which is update as mivion's current version. or  downgrade the nodejs to 6  maybe ok.

**Comment by timotejroiko** [comment]
@keel I tried switching to various node versions, including 6 and the newest 9. problem persists on all of them. I used nvm to switch node version, then used npm install swisseph-new again.

this is the build log for node 6.11

`genesis@genesis-virtual-machine ~/astrobot $ npm rebuild swisseph-new

> swisseph-new@0.5.10 install /home/genesis/astrobot/node_modules/swisseph-new
> node-gyp rebuild

make: Entering directory '/home/genesis/astrobot/node_modules/swisseph-new/build'
  CC(target) Release/obj.target/swissephz/deps/swisseph/swecl.o
../deps/swisseph/swecl.c: In function ‘occult_when_loc’:
../deps/swisseph/swecl.c:2399:11: warning: variable ‘is_partial’ set but not used [-Wunused-but-set-variable]
   AS_BOOL is_partial = FALSE;
           ^~~~~~~~~~
../deps/swisseph/swecl.c: In function ‘swe_get_orbital_elements’:
../deps/swisseph/swecl.c:5457:11: warning: variable ‘ellipse_is_bary’ set but not used [-Wunused-but-set-variable]
   AS_BOOL ellipse_is_bary = FALSE;
           ^~~~~~~~~~~~~~~
  CC(target) Release/obj.target/swissephz/deps/swisseph/swedate.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swehel.o
../deps/swisseph/swehel.c: In function ‘calc_rise_and_set’:
../deps/swisseph/swehel.c:478:1: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
 else
 ^~~~
../deps/swisseph/swehel.c:484:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
   iflag = epheflag|SEFLG_SPEED|SEFLG_EQUATORIAL;
   ^~~~~
../deps/swisseph/swehel.c: In function ‘kOZ’:
../deps/swisseph/swehel.c:831:14: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
   static int a = 0;
              ^
../deps/swisseph/swehel.c: In function ‘time_optimum_visibility’:
../deps/swisseph/swehel.c:2916:31: warning: variable ‘vl’ set but not used [-Wunused-but-set-variable]
   double t1, t2, vl1, vl2, d, vl, darr[10], phot_scot_opic, phot_scot_opic_sv;
                               ^~
  CC(target) Release/obj.target/swissephz/deps/swisseph/swehouse.o
../deps/swisseph/swehouse.c: In function ‘swe_house_pos’:
../deps/swisseph/swehouse.c:1797:47: warning: variable ‘demc’ set but not used [-Wunused-but-set-variable]
   double hpos, sinad, ad, a, admc, adp, samc, demc, asc, mc, acmc, tant;
                                               ^~~~
../deps/swisseph/swehouse.c: In function ‘sunshine_solution_makransky’:
../deps/swisseph/swehouse.c:2455:66: warning: variable ‘cosecl’ set but not used [-Wunused-but-set-variable]
   double sinlat, coslat, tanlat, sindec, cosdec, tandec, sinecl, cosecl;
                                                                  ^~~~~~
../deps/swisseph/swehouse.c:2455:42: warning: variable ‘cosdec’ set but not used [-Wunused-but-set-variable]
   double sinlat, coslat, tanlat, sindec, cosdec, tandec, sinecl, cosecl;
                                          ^~~~~~
../deps/swisseph/swehouse.c:2455:34: warning: variable ‘sindec’ set but not used [-Wunused-but-set-variable]
   double sinlat, coslat, tanlat, sindec, cosdec, tandec, sinecl, cosecl;
                                  ^~~~~~
../deps/swisseph/swehouse.c: In function ‘sunshine_solution_treindl’:
../deps/swisseph/swehouse.c:2598:72: warning: variable ‘equa’ set but not used [-Wunused-but-set-variable]
  double xhs, pole, a, cosa, alph, alpha2, c, cosc, b, sinzd, zd, rax, equa, hc;
                                                                       ^~~~
../deps/swisseph/swehouse.c:2597:33: warning: variable ‘sindec’ set but not used [-Wunused-but-set-variable]
   double mcdec, sinlat, coslat, sindec, cosdec, tandec, sinecl, cosecl;
                                 ^~~~~~
  CC(target) Release/obj.target/swissephz/deps/swisseph/swejpl.o
../deps/swisseph/swejpl.c: In function ‘state’:
../deps/swisseph/swejpl.c:662:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) ch_ttl, 1, 252, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:664:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) js->ch_cnam, 1, 2400, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:668:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_ss[0], sizeof(double), 3, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:672:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_ncon, sizeof(int32), 1, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:676:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_au, sizeof(double), 1, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:680:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_emrat, sizeof(double), 1, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:686:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &ipt[0], sizeof(int32), 36, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:690:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_denum, sizeof(int32), 1, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:693:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &lpt[0], sizeof(int32), 3, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:698:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &js->eh_cval[0], sizeof(double), 400, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:739:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &ts[0], sizeof(double), 2, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:743:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread((void *) &ts[2], sizeof(double), 2, js->jplfptr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c: In function ‘fsizer’:
../deps/swisseph/swejpl.c:200:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &ttl[0], 1, 252, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:202:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) js->ch_cnam, 1, 6*400, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:206:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &ss[0], sizeof(double), 3, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:228:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &ncon, sizeof(int32), 1, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:232:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &au, sizeof(double), 1, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:236:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &emrat, sizeof(double), 1, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:242:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &js->eh_ipt[0], sizeof(int32), 36, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:246:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread((void *) &numde, sizeof(int32), 1, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/swejpl.c:250:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&lpt[0], sizeof(int32), 3, js->jplfptr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/swissephz/deps/swisseph/swemmoon.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/swemplan.o
  CC(target) Release/obj.target/swissephz/deps/swisseph/sweph.o
../deps/swisseph/sweph.c:124:8: warning: missing initializer for field ‘do_interpolate_nut’ of ‘struct swe_data’ [-Wmissing-field-initializers]
        };
        ^
In file included from ../deps/swisseph/sweph.c:72:0:
../deps/swisseph/sweph.h:624:11: note: ‘do_interpolate_nut’ declared here
   AS_BOOL do_interpolate_nut;
           ^~~~~~~~~~~~~~~~~~
../deps/swisseph/sweph.c: In function ‘swe_get_library_path’:
../deps/swisseph/sweph.c:270:12: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
   if(bytes >= 0) {
            ^~
../deps/swisseph/sweph.c: In function ‘load_dpsi_deps’:
../deps/swisseph/sweph.c:1372:14: warning: variable ‘np’ set but not used [-Wunused-but-set-variable]
   int n = 0, np, iyear, mjd = 0, mjdsv = 0;
              ^~
../deps/swisseph/sweph.c: In function ‘jplplan’:
../deps/swisseph/sweph.c:1969:48: warning: parameter ‘iflag’ set but not used [-Wunused-but-set-parameter]
 static int jplplan(double tjd, int ipli, int32 iflag, AS_BOOL do_save,
                                                ^~~~~
../deps/swisseph/sweph.c: In function ‘swecalc’:
../deps/swisseph/sweph.c:3919:5: warning: ‘t’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     swi_bias(xx, t, iflag, FALSE);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/swisseph/sweph.c:3786:10: note: ‘t’ was declared here
   double t;
          ^
  CC(target) Release/obj.target/swissephz/deps/swisseph/swephlib.o
../deps/swisseph/swephlib.c: In function ‘precess_3’:
../deps/swisseph/swephlib.c:1059:10: warning: variable ‘T’ set but not used [-Wunused-but-set-variable]
   double T;
          ^
../deps/swisseph/swephlib.c: In function ‘sidtime_long_term’:
../deps/swisseph/swephlib.c:2949:29: warning: variable ‘t6’ set but not used [-Wunused-but-set-variable]
   double t, t2, t3, t4, t5, t6;
                             ^~
../deps/swisseph/swephlib.c: In function ‘swe_get_astro_models’:
../deps/swisseph/swephlib.c:3971:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_PREC_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3971:44: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_PREC_DEFAULT) imod = 0; break;
                                            ^~~~~
../deps/swisseph/swephlib.c:3973:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_PREC_DEFAULT_SHORT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3973:50: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_PREC_DEFAULT_SHORT) imod = 0; break;
                                                  ^~~~~
../deps/swisseph/swephlib.c:3975:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_NUT_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3975:43: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_NUT_DEFAULT) imod = 0; break;
                                           ^~~~~
../deps/swisseph/swephlib.c:3977:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_SIDT_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3977:44: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_SIDT_DEFAULT) imod = 0; break;
                                            ^~~~~
../deps/swisseph/swephlib.c:3979:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_BIAS_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3979:44: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_BIAS_DEFAULT) imod = 0; break;
                                            ^~~~~
../deps/swisseph/swephlib.c:3981:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_JPLHOR_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3981:46: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_JPLHOR_DEFAULT) imod = 0; break;
                                              ^~~~~
../deps/swisseph/swephlib.c:3983:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_JPLHORA_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3983:47: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_JPLHORA_DEFAULT) imod = 0; break;
                                               ^~~~~
../deps/swisseph/swephlib.c:3985:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (imod == SEMOD_DELTAT_DEFAULT) imod = 0; break;
  ^~
../deps/swisseph/swephlib.c:3985:46: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (imod == SEMOD_DELTAT_DEFAULT) imod = 0; break;
                                              ^~~~~
  AR(target) Release/obj.target/deps/swisseph/swissephz.a
  COPY Release/swissephz.a
  CXX(target) Release/obj.target/swisseph/src/util.o
In file included from ../src/util.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/date.o
In file included from ../src/date.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/swisseph.o
In file included from ../src/swisseph.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/callback.o
In file included from ../src/callback.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/pos.o
In file included from ../src/pos.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/hel.o
In file included from ../src/hel.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/house.o
In file included from ../src/house.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  CXX(target) Release/obj.target/swisseph/src/eclipse.o
In file included from ../src/eclipse.cc:1:0:
../src/swisseph.h:4:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning (disable : 4251)
 
  SOLINK_MODULE(target) Release/obj.target/swisseph.node
  COPY Release/swisseph.node
make: Leaving directory '/home/genesis/astrobot/node_modules/swisseph-new/build'
swisseph-new@0.5.10 /home/genesis/astrobot/node_modules/swisseph-new
genesis@genesis-virtual-machine ~/astrobot $ node main.js 
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/genesis/astrobot/node_modules/swisseph-new/build/Release/swisseph.node: cannot allocate memory in static TLS block
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/genesis/astrobot/node_modules/swisseph-new/lib/swisseph.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`

**Comment by keel** [comment]
@timotejroiko I'm not familiar with glibc or ubuntu, and I have no environment to test it. If I were you, I will try this:
1.Change Ubuntu package server
2.Reinstall all dependency package from new server
3.Reinstall nodejs
I just found this steps from another issue like you, but it may takes a lot of time .

**Comment by timotejroiko** [comment]
@keel The problem seems to be with the architecture. I installed the x64 version of mint 18 this time and it worked. my previous install was x86.

**Comment by mivion** [comment]
@keel could you make a PR, or even add you as contributor?

**Comment by keel** [comment]
@mivion thanks for your trust, I have published the updated version  to npm.

**Comment by mivion** [comment]
@keel, thanks for your help.
Could you create a release tag in repo to be the same as in npmjs.org?

**Comment by keel** [comment]
OK, it's done.

**Comment by mivion** [comment]
👍
