### ISSUE TITLE
nbind for node API

### ISSUE THREAD

**Issue by mivion** [mivion/swisseph#48]
May be we have to move binding api to nbind (https://github.com/charto/nbind)?

It's much simpler and easier to support.

**Comment by keel** [comment]
Maybe we can make a branch to test it. But it will be a strong dependency of nbind.

**Comment by mivion** [comment]
Yes, branch is good idea.

Do you think nbind is good idea?
I've used is on another project, almost no problems, and needs much less copy-paste code.

**Comment by mivion** [comment]
Or maybe we should wait for N-API, mentioned in #42, when it will be available for production?

**Comment by keel** [comment]
I think N-API is better, we can wait ,it's now "Stability: 1",  https://nodejs.org/api/n-api.html

**Comment by mivion** [comment]
Waiting...
