### ISSUE TITLE
Was compiled against a different Node.js version

### ISSUE THREAD

**Issue by albertkai** [mivion/swisseph#49]
After upgrading to Node 8, getting the errors:
`Error: The module '/Users/user/projects/microcosm_alpha/web/node_modules/swisseph/build/Release/swisseph.node'
was compiled against a different Node.js version using  NODE_MODULE_VERSION 48.
This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing.`
Seems the bindings need to be recompiled against the recent node versions

**Comment by keel** [comment]
Maybe you copied the `node_modules` directory to the server, I think run `rm -rf node_modules/swisseph && npm install swisseph` on your server may fix that.

**Comment by albertkai** [comment]
@keel thank you! Yes, the problem was that meteor uses its own node version. After upgrading the system node to the same version that meteor uses everything went good.
