### ISSUE TITLE
Wrong DLL function calling in node_swe_houses_armc

### ISSUE THREAD

**Issue by stsmurfy** [mivion/swisseph#52]
Hi,

In **node_swe_houses_armc** you call **swe_houses** which should be **swe_houses_armc**. It would be great if you could fix it.

Thanks! :)

**Comment by mivion** [comment]
Hi,

It would be grate if you make PR.

Thanks.

**Comment by stsmurfy** [comment]
Okay, I try. I've never done this before and not too familiar with git :)

**Comment by mivion** [comment]
Thanks! Merged.
