### ISSUE TITLE
I'd need swe_azalt()

### ISSUE THREAD

**Issue by David-Gil** [mivion/swisseph#56]
Hi!

For what I want to do, I need to calculate the azimuth. AFAICT, that function is not available. Are there any plans to include it? Is there any way I could help?

I could try to make a PR based on the other function bindings. I think I understand most of it.

**Comment by timotejroiko** [comment]
I have never tested swe_azalt() but it seems to be already present in the package. its defined in swisseph.cc, eclipse.h and eclipse.cc

Do you get any error with it?
