### ISSUE TITLE
 cannot convert from 'initializer list' to 'v8::String::Utf8Value'

### ISSUE THREAD

**Issue by elizabethmeyer** [mivion/swisseph#62]
When I try to install swisseph I get the following error:

`c:\dev\astro\swisseph\src\pos.cc(656): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'v8::String::Utf8Value' [C:\dev\astro\swisseph\build\swisseph.vcxproj]`

Please assist?

**Comment by timotejroiko** [comment]
which node version are you using? if you're using v12, i will soon add a PR to fix many v12 issues, maybe it will fix yours too

**Comment by elizabethmeyer** [comment]
Thank you @timotejroiko - I'll keep an eye out for that.

**Comment by keel** [comment]
please try 0.5.12.
