### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by sstephans** [mivion/swisseph#77]
Do you have any plans to include typescript support for this package?

Thanks so much!

**Comment by krisztianb** [comment]
You mean TypeScript type definitions, right?

Browsing through the depending packages on NPM I found this: https://github.com/milanpredic/astrochart/blob/master/src/%40types/swisseph/index.d.ts

All tough it uses a lot of `any` so I might give it a shot an improve it.

**Comment by krisztianb** [comment]
> If you just want to use swisseph in you project you can always declare the module like
> 
> `declare module "swisseph"`
> 
> You're not going to get any types but at least it is usable.

Sure. That's defining the module without types mapping every type to "any". Which is precisely what you don't want in a TypeScript project. :smile: 

> Btw I am also working on a TS project with swisseph so if anyone is looking for help creating definitions let me know.
> 
> Cheers.

Thanks for letting me know. I'm taking the types from the official Swiss Ephemeris documentation and the C++ code of this project. I'm also adding comments to every function and its parameters to improve intelisense in VSCode for example.

**Comment by roabhi** [comment]
> Sure. That's defining the module without types mapping every type to "any". Which is precisely what you don't want in a TypeScript project. 
> 

Yeah of course, that was the only way for me to at least making the code to transpile with tsc in the meantime but I am looking for a more consistent solution moving forward

> Thanks for letting me know. I'm taking the types from the official Swiss Ephemeris documentation and the C++ code of this project. I'm also adding comments to every function and its parameters to improve intelisense in VSCode for example.

That's just awesome :)

I am not very versed in C++, neither TS as a matter of fact...but will take a look at those types and see if I am able to grasp anything.

Cheers

**Comment by krisztianb** [comment]
PR is open: https://github.com/mivion/swisseph/pull/82
