### ISSUE TITLE
Very Interested and Love to contribute

### ISSUE THREAD

**Issue by appilivamsikrishna** [mivion/swisseph#91]
Hello mivion,

I hope this message finds you well. I am interested in contributing to the swisseph project. Could we discuss this further?

Looking forward to your response.

Best regards,
Krishna

**Comment by mivion** [comment]
Hello.

You are welcome! ))

**Comment by appilivamsikrishna** [comment]
Thank you so much, 

Please let me know what can I improve, like,  do you like to ask me a specific detail of task ?

**Comment by mivion** [comment]
For now it need to support (for example update dependencies and swiseph library) and some times answer questions.
I have no time for now to work on project, so yue free to contribute! )
Also you can see what other contributors do and discuss with then what need to improve.

**Comment by appilivamsikrishna** [comment]
Okay Cool, mivion. Very happy and Excited. :)
